### PR TITLE
Render and export emailable report of past reports

### PR DESCRIPTION
**Pull request by ignaciocabeza**
Hi @fescobar.

The changes I made were:
- Added an extra parameter `report` to `emailable-report/export` and `emailable-report/render`. Default value: `latest`
- Added new parameter to swagger spec.
- Now emailable reports are saved with prefix `{REPORT}_...html`. <- I wonder if this change can break something. Maybe we shouldn't add a prefix when report it's the latest.

Solve #158

### CODE REVIEW

**Comment by fescobar** [comment]
@ignaciocabeza Did you test your changes in the docker container?
I think you should update the Allure repo in the docker files:

```sh
ARG ALLURE_REPO=https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline
```

**Comment by ignaciocabeza** [comment]
I faced that issue when I was configuring the dev environment. There is some issue with the other url. I found a workaround quick with https://github.com/allure-framework/allure2/issues/1198#issuecomment-833791439

And yes, I tried with `docker-compose -f docker-compose-dev.yml up` using some reports that I have from my company.

Again, I wasn't sure about this last change:
> Now emailable reports are saved with prefix {REPORT}_...html. <- I wonder if this change can break something. Maybe we shouldn't add a prefix when report it's the latest.

So, I will do more tests tomorrow (I live in East Australia Timezone) to be sure that the refactor is backward compatible.

Let me know if there is something that may break some other feature.

**Comment by fescobar** [comment]
@ignaciocabeza I have some checks in github actions. You should run those in your GH too. Push the new Allure repo url in the docker files, please. I will check your PR in detail when you passed those checks.
Thanks

**Comment by ignaciocabeza** [comment]
Hi @fescobar,

I activated actions now. It was failing because some pylint error, I fixed it but it's still failing 😖. 

This one are still failing and it comes from my changes:
```
allure-docker-api/app.py:1123:0: R0914: Too many local variables (17/15) (too-many-locals)
```

And the other pylint issues are from code that didn't change related on how do you use `file` without `with`.

---

About this:
> Now emailable reports are saved with prefix {REPORT}_...html. <- I wonder if this change can break something. Maybe we shouldn't add a prefix when report it's the latest.

I refactor the code around `emailable_report_path` and now it's not adding a prefix when report is `latest` (to be backward compatible).

**Comment by fescobar** [comment]
@ignaciocabeza You can disable that rule for this specific method adding this:

```sh
def emailable_report_render_endpoint(): #pylint: disable=too-many-locals
```
Like here but with a different pylint rule
https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-api/app.py#L851

**Comment by ignaciocabeza** [comment]
Hi @fescobar,

I added that lint exception, but other lints no related to my change are still failing:

```
allure-docker-api/app.py:352:8: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
allure-docker-api/app.py:1176:12: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
allure-docker-api/app.py:1569:12: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
```

I can add those exceptions as well. Let me know.

**Comment by fescobar** [comment]
@ignaciocabeza implement the recomendation https://stackoverflow.com/questions/67419064/r1732-consider-using-with-for-resource-allocating-operations-consider-using

**Comment by ignaciocabeza** [comment]
@fescobar Done!

**Pull request closed without merging**
