### PR TITLE
Add support for compressed results upload

### PR DESCRIPTION
**Pull request by arekmadej**
Along with the change to support the upload of compressed results I've made some changes to the provided utility scripts

All of them have now been updated to allow the specification of custom parameters without the need of updating the script itself which is very useful if these are being ran as part of a dynamic CIT environment

README has also been updated to provide more information and example on the new format of scripts

### CODE REVIEW

**Comment by fescobar** [comment]
@arekmadej sorry. I didn't realize about this PR. Instead of updating the files: `send_results.py`  `send_results.ps1` and `send_results.py`. Can you create new files for those scripts?
Also, it would be good if the script contains documentation about how to use it instead of putting that in the readme.
I appreciate your time and let me know your thoughts.
Thank you

**Comment by brizjin** [comment]
fix for a function:
```
def get_results_files(results_dir):
    files_list = []
    for root, dirs, files in os.walk(results_dir):
        for i, file in enumerate(files):
            filepath = os.path.join(root, file)
            files_list.append(('files[]', open(filepath, 'rb')))

    return files_list
```

**Comment by TaylorMcGinnisADI** [comment]
@arekmadej @fescobar @brizjin 
I appreciate the work involved in adding support for zip files, as I am also encountering issues with sending a large amount of report files. Is there anything I can help with to get this PR moved forward?

**Comment by TaylorMcGinnisADI** [comment]
@fescobar any updates on this PR being merged in?

**Comment by sirtomas** [comment]
@arekmadej @brizjin Thanks for all the effort, I have been using this feature for few months and it has been working flawlessly. @fescobar Please is there anything we can do to add this feature to the latest release? Once I add images or videos, the results folder gets unreasonably large to be uploaded without compression. Thank you

**Pull request closed without merging**
