### PR TITLE
Upgrade allure to 2.25.0

### PR DESCRIPTION
**Pull request by nicolabeghin**
Upgrading Allure to latest version due to https://github.com/allure-framework/allure-java/issues/412

### CODE REVIEW

**Comment by nicolabeghin** [comment]
Any update on this? Thanks!

**Comment by nicolabeghin** [comment]
Any update on this? Thanks!

**Comment by nicolabeghin** [comment]
Any update on this? Thanks!

**Comment by fescobar** [comment]
Hi @nicolabeghin 
I'm preparing a PR with multiple updates.
I will be releasing that one this week.
Thank and sorry for the delay.

**Pull request closed without merging**
